### ISSUE TITLE
[Story] Filter challenges by organization

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1035]
Enable to filter challenges by organization.

## Tasks

- [x] Update API description to filter challenges by contributors
- [x] Update the challenge service to filter challenges by contributors
- [ ] Update the client library for Angular
- [ ] #1402
- [ ] #1421

**Comment by tschaffter** [comment]
The Challenge service needs to get information from the Organization service.

- Netflix Feign and Spring RestTemplate (along with [Ribbon](https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-ribbon.html)) are two well-known HTTP clients used for making synchronous API calls. In this [tutorial](https://www.tutorialspoint.com/spring_cloud/spring_cloud_synchronous_communication_with_feign.htm), we will use Feign Client.
  - Ribbon is a client-side load balancer that gives you a lot of control over the behavior of HTTP and TCP clients.
  - Feign already uses Ribbon, so, if you use @FeignClient, this section also applies.

**Comment by tschaffter** [comment]
### Update 2023-03-19

Remaining tasks include:

- [ ] Update API description to filter challenges by contributors
- [ ] Update the challenge service to filter challenges by contributors
- [ ] Update the client library for Angular
- [ ] Update the web app to filter challenges by orgs

**Comment by tschaffter** [comment]
### Update 2023-03-27

The backend of this feature is ready. The frontend behavior is being modified so that typing text in the filter input fields triggers a full-text search using the backend instead of 1) pulling all the results and 2) filtering then at the level of the web app. This will make the behavior of the search input field more consistent across the web app.
