### ISSUE TITLE
Create a service account to access Kaggle API

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1245]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to create a service account so that the service I'm building can access Kaggle API.

### Description

I'm using my personal Kaggle account when developing the Kaggle to Kafka service. This is not secure and prevent me from sharing the credentials with the other developers. The solution to this problem is to create a service account that is not tied to a personal account.

### Acceptance criteria

A Kaggle account has been created and the credentials have been added to LP.

### Tasks

- [x] Create a Google group email address
- [x] Create a Kaggle account with email address `openchallenges+bot@sagebase.org`
- [ ] Story the Kaggle credentials + a Kaggle API key in a shared LP item

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@rrchai Could you take over this ticket? I will send sensitive information over Slack.

**Comment by rrchai** [comment]
ideal username: `openchallengesbot` or `openchallenges`.

**Comment by rrchai** [comment]
update: `openchallenges` and `openchallengesbot` is taken, but no such profile found in kaggle https://www.kaggle.com/openchallengesbot :(

**Comment by tschaffter** [comment]
@rrchai You found the solution. See my message on Slack.

**Comment by tschaffter** [comment]
@rrchai figured out why the Google Group was not receiving emails from Kaggle (for account activation): the group must be configured to receive email from Anyone from the web.

**Comment by tschaffter** [comment]
I created a service account for Kaggle. The credentials and API token are saved to LP under the profile "Kaggle OpenChallenges Service Account".
