### ISSUE TITLE
[Epic] Create Organization search page

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1252]
### As a user, I want

As a prospective challenge organizer, I want to search organizations that have contributed to challenges as cloud provider/data provider/etc., so that I can reach out to them to support my challenge.

### Description

The goal of this story is to enable users to explore organizations that have contributed to challenges. The best way to achieve this is to create an Organization search page that follow the template we have created with the challenge search page.

### Acceptance criteria

- A new search page has been created to explore Organizations.
- The search page can be accessed from the navbar.
- The Organization search page behavior is similar to the Challenge search page.
  - This behavior can be demonstrated using mock or real data.
- Clicking on an organization card lead to its organization page.

Out of scope:

- Adding production data will be tracked in a separate ticket.

### Tasks

- [x] #1268
- [x] #1269
- [x] #1271
- [x] #1347
- [x] #1331
- [x] #1349
- [x] Search Org using full-text search (backend)
- [x] Search Org using full-text search (frontend)
- [x] #1348
- [x] #1378

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Moved to Sprint 23.03

**Comment by tschaffter** [comment]
### Update

There is one ticket left, which the creation of the organization card. Verena has already opened a PR that is under review.

**Comment by tschaffter** [comment]
Done
