### ISSUE TITLE
[Story] Create Organization search page component

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/sage-monorepo#1268]
### What projects is this story for?

OpenChallenges

### As a user, I want

As an organizer, I want to be able to search organizations so that I can find organizations who may be interested in supporting my challenge.

### Description

Create a project for the organization search page. Several features are bundle together in this ticket because they should be almost readily available after copy-pasting the challenge search page to create this new component.

### Acceptance criteria

- The organization search page is accessible in the app (navbar button tracked in another ticket)
- The org search page can generate a query object based on the following filters.
  - Search bar
  - 1 checkbox for the type of organization
  - sorter
- Print the query object to the console.

Out-of-scope:

- Sending the query to the backend.
- Rendering org cards.

### Tasks

- [x] Copy-paste the challenge search page
- [x] Keep only the following components:
  - Full-text search bar
  - 1 checkbox filter
  - Sort menu with only the Relevance option

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
