### ISSUE TITLE
[Story] Identify how to manage the challenge difficulty

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1286]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want to know what the different challenge difficulty mean, so that I can identify the difficulty I'm interested in.

As a developer, I want to know how to set the difficulty property of a challenge so that the difficulty of a challenge is shown in the web app.

### Description

The Challenge data model includes the property `difficulty` that takes an enum value. The goal of this ticket is to identify how we handle this property. There are mainly two questions we need to address:

1. What format do we use for the difficulty value.
2. How to we obtain/generate the difficulty value.

## Difficulty value format

We currently have use the enum [ChallengeDifficulty](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/libs/openchallenges/api-description/src/components/schemas/ChallengeDifficulty.yaml). An alternative could be to use a difficulty numerical score.

## How do we get the value

Initially we planned to let challenge organizer to set the difficulty themselves (enum format) based on the definition we would have given them. Currently, we are moving away from this approach: to make it easier for challenge organizers, we will attempt to collect and update challenge data ourselves.

External challenge information do not include a difficulty value. We can have three options:

1. Set the difficulty value to "undefined".
2. Generate the difficult value ourselves programmatically based on other challenge information available.
3. Generate the difficulty value ourselves manually during before we add the challenge to the DB.
4. In combination with Option 1), enable the challenge organizers to specify this value in an external data source that we would monitor (e.g. REST API, file on github, etc.).

### Acceptance criteria

- We have identified how to manage the challenge difficulty.
- In case where we want to set the challenge difficulty value programmatically, identify how to generate the value (function).
- An implementation plan is devised and approved by Thomas (architect).

### Tasks

- [x] Assign SP estimate to this story
- [x] Review the reference shared by James (see below)
- [ ] Review the different options available to us and identify a strategy

### Anything else?

This story aims to address this [question](https://docs.google.com/document/d/1h7QA7r7Hrstbho5C3F-oGLSTqEKQIXBkSXs5onGpkJs/edit#bookmark=id.dj1hnmqbhj2s) asked by Solly during 2023 January sprint review meeting.

> Q from Solly: How do we select the “difficulty” - As a first step we can ask the organizers, but we should come with some rules around what those definitions will be. 
A from Thomas: Yes, we still need to identify rules. Maybe we could come up with a classifier to automatically assign the difficulty level based on those rules.
A from James: FYI - not exactly a data model for challenge “difficulty” but more for data science training concepts and competencies (so maybe an alternative to categorize challenges and an indirect way to convey difficulty level): https://pubmed.ncbi.nlm.nih.gov/35548703/

We should aim to complete this ticket in February as we are working on the data model and ingress workflow, so that we can share an update with Solly during the next sprint review meeting.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@vpchung I'm tentatively assigning this ticket to you. Let me know if this is something that you could work on this sprint.

**Comment by vpchung** [comment]
@tschaffter I'm happy to take this on, but I'm not confident I'll be the best determine to categorize this.

In the current iteration of the database, I've assigned all challenges as `intermediate` by default, and `advanced` were given to the imaging-related challenges. My reasoning was that imaging data is a specialized data format, and requires more compute power/resources to (pre)process.  Maybe single-cell data should also be 'advanced'?

**Comment by tschaffter** [comment]
Aggregating different information to come up with the difficulty is indeed not an easy task. I think that the main value of our current difficulty model is the "good for beginners" value. In that case, could we just add a flag "good_for_beginners" and set the value manually as we would for the "featured" property?

**Comment by vpchung** [comment]
#### Home Week update

@chepyle and @trberg helped me identify some criteria that could help us recommend difficulty level. I will share next week.

**Comment by tschaffter** [comment]
Moved to Sprint 23.03

**Comment by tschaffter** [comment]
> I’m thinking we could use this [ontology](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9089329/#S11) for the tags?

**Comment by tschaffter** [comment]
### Update 2023-04-03

We decided to down prioritize this ticket, so it's returning to Backlog.

**Comment by tschaffter** [comment]
Closing this feature for now. We can create a new ticket for this feature when it's needed.
