### ISSUE TITLE
[Story] Switch to more performance AWS development instance

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1313]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to have access to enough CPU cores and memory so that I can deploy all the components of the stack.

### Acceptance criteria

- The OC stack can be successfully deployed in the dev container with 3-node ES cluster and 3-node Kafka cluster.

### Tasks

- [x] Identify a suitable, more performance EC2 instance type for development.
- [x] Switch one development environment to the new instance type and check ACs (Thomas)
- Prepare the `t3.2xlarge` instance and stop/remove the `t3a.xlarge` instance.
  - [x] Rong
  - [x] Verena
  - [x] Thomas

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
> T - These types support bursting CPU usage at any time and as long as you need. Each generation has some unique features. In particular, the T4g general-purpose instance type uses AWS Graviton2 processors, which are 40% more efficient than T3 processors. These instances are ideal for web development, testing, and microservices projects. 

[Source](https://www.cloudzero.com/blog/aws-instance-types)

**Comment by tschaffter** [comment]
All the members of the team have switched to a `t3.2xlarge` instance.
