### ISSUE TITLE
[Story] Enable users to register to the OC mailing list

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1335]
### What projects is this story for?

OpenChallenges

### As a user, I want

As an unregistered user, I want to subscribe to the OC mailing list so that I can be informed about the OC activities without having to create an account.

As a beta tester, I want to subscribe to the OC mailing list so that I receive communication when the app launches publicly.

### Description

The goal of this Story is to enable anyone to subscribe to the OC mailing list via the app.

We should also discuss whether this story should also enable people to remove their email from the mailing list or if this could be implemented later.

## Examples

From HeroX:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/3056480/220655180-374d2ddd-c348-4867-a7c6-16cae76985ae.png">

### Acceptance criteria

- The UI component to subscribe should be visible and findable on the app.
- The app now includes a component that allows anyone to add their email address to the OC mailing list.
- The person receives a confirmation that their email has been successfully registered.
- The content of the mailing list is private and secured.

Out of scope:

- How to use the mailing list
- Unregistering email address initially (TBD)

### Tasks

- [ ] Create a UI component to add email address to the OC mailing list
- [ ] Create REST API endpoints to manage the OC mailing list

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
A mailing list is not needed at that time.
