### ISSUE TITLE
[Story] Add smart imaging service to OC

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1365]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want the OC app to download only the image information needed - and not images larger than needed - so that the pages and their content load faster.

As a developer, I want to be able to add an image in the OC app with minimal processing so that I can focus on building the feature I'm working on.

### Description

Here is a typical workflow adopted by developers when adding an image to a web app:

- Locate and download the image from a third-party website
- Add the source image to the codebase (e.g. GitHub)
- (Optional) Process and save different version of the image. Example operations include:
  - Cropping the image to fit an aspect ratio defined by the UI layout
  - Generating different image size to optimize page loading speed (e.g. small, medium, large size of an image)
- Use the image in the codebase

## Pain points

- Image processing is done manually
  - Repeating this work is time consuming (e.g. the size of "small" images may increase over time as screen resolutions increase)
  - manual operations may lack proper documentation or docs may be deprecated (there is a maintenance cost for docs)
- Version control binary files with git slows it down. As we work in a fast-growing monorepo, especially as more projects may be onboarded, we need to take extra measures to make sure that the monorepo remains lean.

## Architecture

Add a smart imaging service like Thumbor or imagor to programmatically process images. These services can fetch images from a filesystem, S3 or Google bucket as well as other data sources.

Here is how a developer would now work with a new image:

- Locate an image hosted on a third-party website and copy its URL
- Use the image in the app code with a URL similar to `https://smart-imaginging-service/<operations>/<image url>` where `operations` could be a chain of processing operation, e.g. resize + grayscale with `300x300/grayscale/`.

To prevent broken image in case a third-party website that hosts the image is down, the developer would instead:

- Locate and download the image from a third-party website
- Add the image to a file or object storage (e.g. S3 bucket, "asset" git repository, etc.) that the smart imaging system is configured to access.
- Use the image in the app code with a URL similar to `https://smart-imaginging-service/<operations>/<image key>` where `<image key>` is a unique identifier that the smart imaging service can use to retrieve the image.

## Existing solutions

- [Thumbor](https://github.com/thumbor/thumbor) is a mature solution that offers a large number of operations and different types of data sources from where it can retrieve images.
- [imagor](https://github.com/cshum/imagor/graphs/contributors) is a spiritual alternative/successor to Thumbor developed in Go. The authors started this project because they evaluated that Thumbor was no longer actively developed.

I would first give a try to Thumbor because:

- I hused Thumbor in a project a few years ago.
- Thumbor has more features than imagor.
- Thumbor is supported by a larger community than imagor (imagor is mainly developed by one person)

### Acceptance criteria

- The imaging service can be deployed with Docker.
- There is a clear documentation that describes how to manage images (add, update, remove).
- The web app includes at least one image provided by the imaging service.
- There is a consensus among the OC team members that the imaging service improves UX and DX (developer experience).

### Tasks

- [x] #1366
- [x] #1390
- [ ] Document how to add, remove, edit images when using Thumbor
- [ ] Update the OC app to use one image served by Thumbor

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Tentatively adding to this active sprint (23.03)

**Comment by tschaffter** [comment]
Duplicate of #1386
