### ISSUE TITLE
[Epic] Measure how users interact with the OpenChallenges content

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1400]
### What projects is this story for?

OpenChallenges

### As a user, I want

As the Product Owner, I want to know how the users interact with the OC content so that I can identify a baseline usage and measure future improvement.

As a frontend developer, I want to access information about how the users interact with the web app (time spent on each page, navigation flow) so that we can improve the navigation and the content of OC.

### Description

The goal of this story is to identify and deploy a solution to measure how users interact with the OpenChallenges content. The information collected should help to build a baseline of how users interact with OC as well as enable to measure the impact of future features. Example of metrics includes the number of page views, time spent on OC, from where the users come from (e.g. Google, LinkedIn, etc.), etc. This information will be useful to the management team, stakeholders and users (e.g. we aim to show at least basic stats like the number of page views to users).

### Tasks

- [x] #676
- [x] Deploy and explore at least one analytics solution
- [ ] Identify the metrics that we want to collect during the private preview and onward
- [ ] Document how to access the analytics data
- [ ] Explore how to enable users to access the number of page views
- [ ] Implement minimal solution to enable users to access the number of page views

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Returning to the Backlog: this will be more relevant for the beta launch later this year when we expect a larger number of users to interact with the app.

**Comment by tschaffter** [comment]
Added to Backlog

**Comment by tschaffter** [comment]
No longer a requirement
