### ISSUE TITLE
[Story] Create imaging service that interacts with Thumbor

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1407]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a backend developer, I want to limit users to fetching only the images that are meaningful so that we do not expose ourselves to high storage and compute costs.

As a frontend developer, I want to be able to consume images in different format so that I can decreasing the loading time of the pages.

### Description

The goal of this story is to develop a microservice that will serve images from Thumbor.

The first motivation is to prevent users from using the full range of Thumbor operations, which could expose us to high cost (S3 storage and compute hours). Thumbor provides a mechanism to prevent users from modifying the URL by signing the Thumbor URL. However, this can only be done safely from a service and not from the web app.

The second motivation is that we will write an API description for this service, which will give us an Angular client for free.

### Acceptance criteria

- Fetch an image from the imaging service from the web app.
- The URLs returned by the imaging service are signed.

### Tasks

- [x] #1409
- [x] #1412
- [x] #1414
- [ ] Generate an API client for Angular to fetch images from Thumbor
- [ ] Fetch an image from the imaging service from the web app
- [x] #1416

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Sprint 22.04

**Comment by tschaffter** [comment]
Here is the architecture for managing images in OpenChallenges.

![image](https://user-images.githubusercontent.com/3056480/227279112-67965340-e973-4082-9dda-04a5930294b5.png)

**Comment by tschaffter** [comment]
Done
