### ISSUE TITLE
[Story] Accelerate the build of the docker images

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1435]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I would like that building the images I need to contribute to the OC stack is as fast as possible so that the risk of context switching are reduced to a minimum.

### Description

Building all the docker images of the OC stack currently requires the execution of 47 tasks, including building and installing Java libraries, and building Java services. Building the images is easily accomplsihed with `openchallenges-build-images`. Running this command a second time shows the current number of tasks that are/can be cached (10 out of 47 tasks) as well as the smallest time it takes to build all the images (~4 minutes).

```console
$ openchallenges-build-images

...
 >  NX   Successfully ran target build-image for 24 projects and 23 task(s) they depend on (4m)
 
   Nx read the output from the cache instead of running the command for 10 out of 47 tasks.
 
   View logs and investigate cache misses at https://cloud.nx.app/runs/f79VPi294j


real    3m47.532s
user    1m18.754s
sys     0m21.118s
```

The goal of this ticket is to explore how to reduce the build time to a maximum. If we can reduce this time to less than 30 seconds, we would then become acceptable to build the images automatically with git hooks, e.g. after a `git checkout` so that the developers is always working with the latest version of the images.

### Acceptance criteria

- All the tasks involved in building the OC images have been identified
- Among these tasks, we have identified whether we can start caching new tasks
- We are now caching all the tasks that we can
- 2 story points have been spent

### Tasks

- [ ] Identify the tasks that are currently not cached that we could cache (in the context of build images)
- [ ] Start caching the tasks identified

### Anything else?

There are two approaches complementary approaches that we could take to reduce the build time of the images:

1. Cache more tasks
2. Build only the images that the developer needs

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
The build time is currently not an issue.
