### ISSUE TITLE
[Story] Streamline and document how developers should manage the confif of components

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1437]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to be aware when a config change requires an action from me, so that I can prevent the OC stack from breaking.

As a developer, I want to know how I can change the config of a component without affecting the work of other developers.

### Description

The OC stack is composed of a large number of components (> 20) and managing their configuration should be well documented. One goal is to ensure that developers are not faced with a broken stack because the config is no longer valid. Recently onboarded developed should also be aware of how to configure their local stack to access private resources.

As an example, the config server requires the developer to be invited to get access to the git repo that includes config data served by the config server. The developer must then update the `.env` file of the config server with a GH API token so that their instance of the config server can access the configuration.

Another issue is that only microservices currently get their config data from the config server. Ideally, all the components of the stack should get their config in the same way, including DBs and the web client.

### Tasks

- [ ] Review the OC projects that must be manually configured by each developer
- [ ] Design an architecture that minimize the actions that developers must take to keep their configuration up to date

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Returning to Backlog

**Comment by tschaffter** [comment]
Added to Backlog
