### ISSUE TITLE
[Story] Find/create illustrations for the OC web client

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1454]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user, I want the different sections of the OC app to be illustrate with images so that I can feel more engaged with the content and mission of OC.

### Description

Work with the Design team to design some graphics that can be used on the app.  More details provided in the DESIGN Jira ticket: https://sagebionetworks.jira.com/browse/DESIGN-1181

### Acceptance criteria

Receive graphics from Stockard and upload them to our S3 bucket, maybe into a folder called `graphics`?

### Tasks

- [x] Reach out to Stockard from Design
- [ ] Iterate through possible graphics to be used on the OC
- [x] Share with the team for feedback
- [ ] Receive graphics
- [ ] Upload graphics to our S3 bucket

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
#### 5/1 Update
I have [sent a request](https://sagebionetworks.jira.com/browse/DESIGN-1181?focusedCommentId=171904) to retrieve the graphics so that we can start adding them to the app.

Excited!

**Comment by vpchung** [comment]
Images have been downloaded and added to the S3 bucket.
