### ISSUE TITLE
[Story] Write a unit test for the enpoint of the image service

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1456]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want a reproducible way to test the implementation of a microservice so that I and the CI workflow can run the tests easily.

### Description

The goal of this story is to write unit tests for the single endpoint of the image service. This service is a good candidate for starting to write unit test because it has no dependency (e.g. DBs). Technically, the service does not even need Thumbor to run to work, though Thumbor is currently deployed as a dependency of the image service.

### Acceptance criteria

- The unit tests can be run with `nx test openchallenges-image-service`.
- The above command is successful.

### Tasks

- [x] Add the definition of the `test` task to the image service
  - See the `auth-service` file `project.json` for an example
- [x] Update the file `build.gradle` to support unit and integration tests
  - See this [example](https://github.com/Sage-Bionetworks/sage-monorepo/blob/515db23f619b1a52780a75b5387a5cd01af2c2e0/apps/openchallenges/user-service/build.gradle.old#L24-L48) may be useful (look for references to "test" in the entire file)
- [x] Create a unit test file to test the endpoint of the image service
  - See this [example](https://github.com/Sage-Bionetworks/sage-monorepo/tree/515db23f619b1a52780a75b5387a5cd01af2c2e0/apps/openchallenges/user-service/src.old)

### Anything else?

Searching for Medium or Baeldung articles on how to write unit and integration test for Sprint boot service could help. I believe that the standard is now to use JUnit 5 (ignore JUnit 4 solution as I believe quite a few things have changed since).

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@mdsage1 Tickets linked to a PR are closed when the PR is merged. Tickets that are not implemented by a PR can be closed manually.
