### ISSUE TITLE
[Story] Enable the user of the image service to specify the image dimension

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1457]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to specify the dimension of the image to the image service so that the app can download an image of the proper size without wasting resources and slowing down the loading of the pages.

### Description

There are a few images that the OC app displays in different size. For example, the logo of organizations is displayed in at least two different size: 1) on the cards shown on the organization search page and 2) on the organization page.

One of the motivations for integrating Thumbor to the stack is to resize images on the fly so that the OC app downloads images with the required size and thus avoid loading large images when smaller version of them are enough. The size of a given image may also depend on whether the app is displayed on a small or larger screen (e.g. smartphone, laptop, desktop monitor).

One of the motivations for using the image service as a middleware is to restrict the operations that the users can apply to images (e.g. resizing, flipping, applying filters). This is required to avoid the generation and storage of large amount of data that would become expensive.

The goal of this ticket is to modify the image service so that the user can specify the "size" of the image required, while limiting the possible size to a predefined set. Because the user can not specify the exact image size they want, the idea is that they select the image size allowed which is the closest to the one needed, then further resize - usually downsize - the image on the HTML page.

### Acceptance criteria

- The user can request the size of the image needed among a set of predefined image sizes.
- The image size accepted by the image service are defined in the config file.
- The image service returns a valid image URL that includes information about the image size.

### Tasks

- [x] Identify the image sizes that the image service should support
    - Discuss with Verena what image sizes are needed for the OC web app
- [ ] Update the OC API description to enable the user to specify the size of the image needed
- [ ] Update the image service to display the image size requested (using the Logger)
- [ ] Define in the image service a set of image sizes that are accepted
    - Consider the benefit of defining this information in the OC API description
- [ ] Return an error if the user requests an invalid image size
- [ ] Return a valid image URL that includes information about the requested image size

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by mdsage1** [comment]
The card components are using 140x140 and profile pages are using 250x250

**Comment by tschaffter** [comment]
@mdsage1 @vpchung Here are additional details on the design of the solution to implement in this ticket (please also refer to the Tasks section above):

- We should assume that the user of the image - i.e. the frontend developer - does not know the size and aspect ratio of the original image available on S3. Requiring the developer to check the original size of the image in the S3 bucket would not be practical.
- The aspect ratio of an original image can be anything.
- We want to allow the user to "roughly" specify the size of the image they need in the web app. Here the word "roughly" is important because we can not allow the frontend developer to request the exact size of the image needed, otherwise we would expose ourselves to high S3 cost (hint: we are caching processed images in a second S3 bucket).

The solution I propose is to update the image service to allow the user to specify an image size among a predefined set of image sizes. Let's say that we offer only 3 image size, then it means that we can have at most 3 cached version of a given image, thus limiting S3 cost.

Now the user does not know the aspect ratio. Hence, let's only ask the user for the `width` of the image and then enforce Thumbor to return an image that respect the aspect ratio of the original image. Therefore, we could update the image service to access the property `width` with accept values from an Enum.

Using OpenAPI description, the new parameter could be:

[libs/openchallenges/api-description/src/components/schemas/ImageQuery.yaml](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/libs/openchallenges/api-description/src/components/schemas/ImageQuery.yaml)

```yaml
type: object
description: An image query.
properties:
  objectKey:
    description: The object key of the image.
    type: string
    example: logo/dream.png
  width:
    description: The width of the image.
    type: string
    default: original
     enum:
      - original
      - 100px
      - 300px
      - 500px
required:
  - objectKey
```

With the above example, at most 4 versions of an image may be cached on S3.

@vpchung As a stakeholder of this story, does the proposed design looks good to you?

**Comment by tschaffter** [comment]
Added to Sprint 23.05

**Comment by tschaffter** [comment]
@mdsage1 The task #1481 is a better candidate than the present task to learn how to modify the OpenAPI description of the app and use OpenAPI generator to update the microservice in Java, as #1481 requires less modification to be done to the API description.
