### ISSUE TITLE
[Story] Allow user/data curator to specify the avatar initials for organizations

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1481]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a user/data curator, I want to be able to customize the initials displayed in the avatar (when no image is available) so that I can prevent "mistakes" made when inferring the initials from the name of the organization.

The same could apply to users when we resume working on the user implementation.

### Acceptance criteria

Out of scope:

- Frontend code would be updated in a separate PR, including updating the API client for Angular.

### Tasks

- [x] Add the property `organization.acronym` to the API description
- [ ] Add the property `organization.acronym` to the data model
- [x] Update the organization service to support the new parameter
- [ ] #1520

### Anything else?

- This is a good task for Maria as part of her onboarding.
  - Minimal change made to the API description + update of one microservice
  - Collaboration with another developer in the same PR (Verena will update the data)
- This feature was suggested by Solly during the April sprint review meeting.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@vpchung How would you like to address this "issue" mentioned by Solly?

**Comment by vpchung** [comment]
Hmm...  One possible option would be to add `shortName` back to the data model, which is already included in our OpenChallenges Data google sheets. (I had added it so that we can more easily generate a slug name/login).

For example, I saw that James mentioned that the acronym for University of Illinois Urbana-Champaign is UIUC, not UOIU, and this is reflected with what we currently captured in our [google sheets](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1828426045) as well :-)

Going with this route does come with the caveat in that not every organization may have a short name.  But in that case, we could default back to what we are currently doing, where we take the first letter of every word in the organization name?  We can also additionally remove any instances of "of" and "the" and "and" before taking the initials, which would address Solly's observation.

**Comment by vpchung** [comment]
^ oh wait... another possible issue is that not every short name will be an acronym.... in that case, maybe instead of `shortName`, we add `acronym` to the data model?

What are your thoughts? @tschaffter @mdsage1

**Comment by tschaffter** [comment]
@vpchung I like your suggestion to add the property `acronym` to the data and API models. Having a "short name" wouldn't solve the issue raised by Solly as the short name may still include token like "of", which would still lead to the avatar component to generate "incorrect" initials.

@mdsage1 This PR is a good opportunity for you to learn:

- How to update the API model
- How to update a microservice with OpenAPI generator
- Work on a story in collaboration with other developers

Here are the tasks:

- [x] @tschaffter to create the branch [issue-1481](https://github.com/Sage-Bionetworks/sage-monorepo/tree/issue-1481) on upstream (official repo)
- [ ] @mdsage1 to create a new branch from `issue-1481` to
    - update the API description of the organization service to add the property `Organization.acronym`
    - update the data model of the organization service (SQL)
- [ ] @tschaffter to create a new branch from `issue-1481` to update the web app to use the org acronym (when available) for the generation of the avatar
