### ISSUE TITLE
[Story] Add CDKTF project that deploys a single resource on AWS

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1485]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a DevOps, I want to be able to explore how to use Terraform CDK (CDKTF) to deploy the infrastructure resources so that I can use my favorite programming language to perform this operation.

The same could apply to users when we resume working on the user implementation.

### Tasks

- [ ] Create a TypeScript boilerplate project with CDKTF and name it "openchallenges-infra"
- [ ] Modify `main.ts` to instantiate an EC2 instance
- [ ] Define Nx tasks for this project: lint, build, deploy, destroy
- [x] #1493

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
