### ISSUE TITLE
[Story] Add unit test for getting a single organization

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1528]
### What projects is this story for?

OpenChallenges

### As a user, I want

NA

### Description

The goal is to enable unit testing in the organization service. A single unit test is required to demonstrate that the unit testing framework works.

### Acceptance criteria

- The endpoint to get a single organization is covered by a unit test

### Tasks

- [x] Configure the organization service to support unit testing
- [x] Add a unit test for the endpoint that returns a single organization

### Anything else?

An example is available in the PR that added unit testing to the image service.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
Return to Backlog

**Comment by mdsage1** [comment]
The Organization Service module had no tests for OrganizationService.java.
![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/b3efc077-ec3e-4722-94f5-61802e667085)
Additional Unit Tests added to improve coverage. Sonar will provide updated coverage once PR created.
Current coverage shows:
![image](https://github.com/Sage-Bionetworks/sage-monorepo/assets/122999770/919bbbc0-8c7b-45a6-a815-62a960f07de6)
PR #2507 covers the changes implemented.
