### ISSUE TITLE
Disable Sleuth in microservice with a configuration parameter

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1549]
### What projects is this story for?

OpenChallenges

### As a user, I want

NA

### Description

The logs of the microservices show errors from Sleuth when Sleuth cannot push traces to Zipkin, which is currently not deployed as part of the stack with Docker.

### Tasks

- [ ] Add a parameter to the config file of the microservice to enable/disable Seuth
- [ ] Update the code to enable Sleuth based on the value of this parameter.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Backlog
