### ISSUE TITLE
[Story] Upgrade all legacy Angular components

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/sage-monorepo#1554]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a frontend developer, I want to refactor the app so that all components used are not the legacy ones, e.g.

```
import { MatLegacyButtonModule as MatButtonModule } from '@angular/material/legacy-button';
import { MatLegacyCardModule as MatCardModule } from '@angular/material/legacy-card';
import { MatLegacyFormFieldModule as MatFormFieldModule } from '@angular/material/legacy-form-field';
import { MatLegacyInputModule as MatInputModule } from '@angular/material/legacy-input';
```

### Description

IIRC, we had a ticket for this before but I am unable to find it.

### Acceptance criteria

The app no longer uses the legacy themes or styling.

### Tasks

Fix the following page components:

**apps/openchallengs**
- [x] _app-theme.scss
- [x] app.module.ts 

**libs/openchallenges**
- [ ] challenge.module.ts
- [ ] challenge-search.module.ts
- [ ] statistics-viewer.module.ts
- [ ] login.module.ts
- [ ] not-found.module.ts
- [ ] org-profile.module.ts
- [ ] signup.module.ts
- [ ] navbar.module.ts
- [ ] user-button.module.ts
- [ ] user-profile.module.ts

### Anything else?

This should fix some styling issues currently seen in the app, e.g. button themes do not work as expected, which I'm suspecting is due to the [usage of legacy components](https://stackoverflow.com/a/69098711).

![Screen Shot 2023-05-15 at 10 53 06 AM](https://github.com/Sage-Bionetworks/sage-monorepo/assets/9377970/3067931c-cb59-443f-87cf-c5bdd3a8ef50)

(For now, I will be applying the colors directly to the buttons)

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
Move to Aug sprint.

**Comment by tschaffter** [comment]
@vpchung The responsibility of moving tickets to different sprints falls on the Project Manager (me) as part of the sprint preparation activity.

**Comment by tschaffter** [comment]
When updating the signup component to use standalone components, I observed that the app build successfully when using:

```typescript
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
```

instead of

```typescript
import { MatLegacyFormFieldModule as MatFormFieldModule } from '@angular/material/legacy-form-field';
import { MatLegacyInputModule as MatInputModule } from '@angular/material/legacy-input';
```

The issue is that the UI looks different, so I will keep using the legacy components until work on the present ticket start.

Using the legacy components mentioned above:

<img width="1440" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/196c73d8-2b36-46d8-a40e-c7242dd29abb">

Using the new components mentioned above:

<img width="1440" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/e7691109-8c2b-44ad-8bd3-b8cc99d0203c">

**Comment by tschaffter** [comment]
From a blog post on Angular v16 (latest version used in Sage Monorepo):

> A reminder that we’ll be removing the legacy, non-MDC based components in v17. Make sure you follow our [migration guide](https://github.com/angular/components/blob/main/guides/v15-mdc-migration.md) to move to the latest.

Source: https://blog.angular.io/angular-v16-is-here-4d7a28ec680d

**Comment by vpchung** [comment]
### 8/29/2023 update:

Given my current priorities, I did not have time to work on this ticket this sprint.

**Comment by tschaffter** [comment]
Moving to Sprint 23.09.

**Comment by vpchung** [comment]
FIN!!!! 🎉 

(finally)
