### ISSUE TITLE
[Story] Connect to the bastion with AWS SSM

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1591]
### What projects is this story for?

OpenChallenges

### As a user, I want

NA

### Description

IT recommends connecting to the bastion using AWS SSM instead of using SSH.

Using SSH would require Sage to update the network to allow SSH connection from an EC2 created from the Service Catalog. With SSM no change to the network are required.

### Tasks

- [x] Create an instance profile
- [x] Attach a role with the policy `arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore` to the profile

### Anything else?

- [How to unit test the role is set in the IamInstanceProfile using cdktf](https://stackoverflow.com/questions/75886754/how-to-unit-test-the-role-is-set-in-the-iaminstanceprofile-using-cdktf)
- [Terraform: aws_iam_instance_profile](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_instance_profile)
- [AWS IAM Role and Instance Profile Explained](https://devopscube.com/aws-iam-role-instance-profile/)

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
