### ISSUE TITLE
[Story] Setup DNS for preview.openchallenges.io

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1597]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to check that requests sent to preview.openchallenges.io can create the preview EC2 instance.

### Acceptance criteria

- In a browser, navigating to preview.openchallenges.io will show a response returned by a service running on the preview instance.

### Tasks

- [ ] Read [Managing Route53 DNS with Terraform and CDK in 100 LOC or less](https://kerrywilson.dev/post/2021/08-12-managing-route53-dns-with-terraform-and-cdk/)
- [ ] Implement the solution described in the above article
- [ ] Work with Xa to check that the solution works (need changes to Sage IT AWS account)

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to Sprint 23.06

**Comment by tschaffter** [comment]
## Update 2023-07-03

I'm working with @xschildw on this ticket. It should be almost done.

**Comment by tschaffter** [comment]
Added to Sprint 23.07

**Comment by tschaffter** [comment]
## Update 2023-07-31

I will attempt to address the suggestions made by Xa today.
