### ISSUE TITLE
[Story] Add public ALB in front of the preview instance

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1598]
### What projects is this story for?

OpenChallenges

### Description

Enable a user to send requests to the preview instance. Adding a public ALB in front of the preview instance should be the way to go.

### Acceptance criteria

- A request sent to the public IP of the ALB returns a response from the preview instance

### Tasks

- [ ] Run a dummy HTTP server on the preview instance so that the instance can respond to requests
- [ ] Add an ALB in front of the preview instance

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Duplicate of #1589
