### ISSUE TITLE
[Story] Collect the logo of the challenge platforms

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1614]
### What projects is this story for?

OpenChallenges

### As a user, I want

NA

### Description

Collect the logo of the challenge platforms. The logos will be used in the Platform filter of the challenge search page.

### Tasks

- [x] Collect the logos of the challenge platforms (aspect ratio 1:1) that we have in the OC DB and add them to the S3 image bucket.
- [ ] Add the property `avatarKey` to the challenge platform objects in the DB.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by vpchung** [comment]
[Already collected](https://docs.google.com/spreadsheets/d/1XRSUVqbZk_k9_rV1vpgPVMQ0fVV0mavwY8Aqyy0C2HQ/edit#gid=1744053577) :-)
