### ISSUE TITLE
[Story] Identify infrastructure diagram for Schematic 2.0

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1672]
### What projects is this story for?

Schematic

### As a user, I want

NA

### Description

Create an infrastructure diagram for the FAIR Data stack.

Known stack components:

- Data Curator App (DCA)
- Schematic REST API
- Synapse REST API
- Data Flow App (DFA)
- Schematic DB

### Tasks

- [ ] Discuss with the members of the FAIR Data team to clarify how some components fit into the "FAIR Data" stack(s).
- [ ] Create a diagram of the current architecture
- [ ] Create a diagram of the proposed new architecture

### Anything else?

Cc: @linglp @milen-sage 

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by milen-sage** [comment]
"As a solutions architect I want to know what is the existing stack and communication flow between different modules in the schematic framework  - both frontend (DCA, DFA) and backend (schematic, schematic-db, schematic REST API) - across high priority user stories, so that I can optimize the system for efficient performance (i.e. satisfying QoS guarantees)  and maintainability (i.e. reducing number of bugs and time to their resolution; reducing time for adding new features)."

**Comment by milen-sage** [comment]
@tschaffter the tasks make a lot of sense. I added a sentence in a form of a user story, although it's not quite a user story and not quite a user scenario and can be refined more :)

**Comment by tschaffter** [comment]
The creation of the Software Architect role is still unclear. We can reopen this ticket once the creation of the role is confirmed.
