### ISSUE TITLE
[Story] Push OC images to GHCR

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1708]
### What projects is this story for?

OpenChallenges

### As a user, I want

As a DevOps, I want the OC images to be pushed to GHCR as part of the CI/CD workflow.

### Description

See #1695 for additional context

UPDATE: This ticket initially aimed to push images to Docker Hub. After evaluation, GHCR seems to be a better fit in terms of least privileges access.

### Acceptance criteria

- The OC images are pushed to GHCR as part of the CI/CD workflow

### Tasks

- [ ] Do a quick research spike on how to assign a version number to the OC images
- [ ] Update the CI/CD workflow to push the images to Sage Docker Hub account

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
There are a few images that have be exclude because of the max storage space available to the GH runner. The remaining images will be built in a subsequent PR.
