### ISSUE TITLE
[Epic] Biannual Dependency Upgrade (2023 Q3)

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1804]
### As a user, I want

As a Developer, I want to update regularly the dependencies we use so that we have access to the latest and most secure tools.

### Tasks

- [x] #1842
- [x] #1860
- [x] #1865
- [ ] Update Maven wrappers
- [ ] Update OpenAPI Generators

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
