### ISSUE TITLE
[Task] Onboard Lawrence Li to Sage Monorepo

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2004]
### Description

Onboard Lawrence to Sage Monorepo.

## Tasks

- [x] Create an EC2 instance for remote development (see [instructions](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/docs/develop-on-a-remote-host.md))
    - Tag the EC2 with valid tags for your team (e.g. cost center)
- [x] Watch this [video](https://youtu.be/ig_BbCuQNdw) for more information about Sage Monorepo dev container
- [x] Identify the structure of the Agora product(s)
- [x] #2038
- [x] Create boilerplace Angular lib for Agora

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Done
