### ISSUE TITLE
[Story] Remove EasyChair and Drupal as Platforms ⭐

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2205]
### What product(s) is this story for?

OpenChallenges

### Description

Gustavo challenges the fact that EasyChair should be considered as a platform. EasyChair is currently listed as a platform in OC.

### Tasks

- [x] Identify if EasyChair is a platform (related to the crafting of the definition of what a challenge platform is in a separate ticket)
- [x] Remove EasyChair from OC Data (use "other" for the challenge platform)
- [x] Remove Drupal from OC Data (use "other" for the challenge platform)
- [x] Remove EC and Drupal logo from the home page
- [ ] Update the OC DB (CSV files)

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
@gaiaandreoletti I went through the process of submitting an abstract for a talk with EC. The submission was a form and the abstract was copy-pasted to a text area. EC does not have challenge-specific features such as a leaderboard. Hence, we should remove references to EC has a "platform" from OC.

**Comment by tschaffter** [comment]
Added to Sprint 23.11

**Comment by gaiaandreoletti** [comment]
both Drupal and Easychair were removed from OC Data spreadsheet

**Comment by tschaffter** [comment]
@vpchung See remaining tasks in the original post.

**Comment by vpchung** [comment]
So for CAGI challenges, would we say their platform is Synapse or CAGI?

**Comment by tschaffter** [comment]
I like the 5 challenges per row as it takes better advantage of the horizontal space (Option 2 or 3).

**Comment by gaiaandreoletti** [comment]
@tschaffter removed and indicated as FALSE in the OC data-spreadsheet so they do not compare as platform

**Comment by vpchung** [comment]
> @tschaffter removed and indicated as FALSE in the OC data-spreadsheet so they do not compare as platform

Gotcha.  So challenges can still list "Drupal" as a platform then?  We will just not display Drupal on the planned Search Platforms page?

**Comment by gaiaandreoletti** [comment]
oh no, i removed it and put as "other"

**Comment by tschaffter** [comment]
@vpchung @gaiaandreoletti Drupal should not be tracked as platform. Removing its logo was correct.

**Comment by vpchung** [comment]
> oh no, i removed it and put as "other"

Okay, perfect!  The latest updates will be reflected in the data push on Monday.
