### ISSUE TITLE
[Story] Add Kibana to the OC stack

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2214]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

As a Developer, I want to access the logs generated by the components of the OC stack in a centralized place so that I can quickly identify the logs I'm looking for.

### Description

Add Kibana to the OC stack as a container project.

### Tasks

- [ ] Add the project `openchallenges-kibana`
- [ ] Enable Kibana to access data stored in ES
- [ ] Add health check to the docker image of Kibana
- [ ] Deploy Kibana along the rest of the OC stack
- [ ] Add a redirecting to Kiaban to Apex config

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Added to backlog
