### ISSUE TITLE
[Task] Improve the quality of the team members' pictures ⭐

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2289]
### What product(s) is this story for?

OpenChallenges

### Description

The existing images are pixelated. This could be because of the source images or because of Thumbor processing.

This issue was reported by Drew.

### Tasks

- [ ] Identify why the images are pixelated
- [ ] Fix the images
- [ ] Let Drew know that the issue has been fixed

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by rrchai** [comment]
>  Identify why the images are pixelated

Several factors might be contributing:

- Thumbor defaults to converting non-jpeg images to jpeg. This conversion process can alter the image size. For instance, during a test, a 460x460 png image titled "text_quality.png" was resized to 460x400 in jpeg format. However, jpeg images maintained their original size post-conversion. You can prevent this auto-conversion using the [autojpg](https://thumbor.readthedocs.io/en/latest/autojpg.html) filter.
- By default, Thumbor compresses the image quality to 80% of its original value. To adjust this, use the [quality](https://thumbor.readthedocs.io/en/latest/quality.html) filter.
- The source image might not have a great quality.

>  Fix the images

I can try to add configuration of Thumbor to turn off the autoJPG conversion and maintain full image quality. However, I doubt this will yield noticeable improvement. A more effective solution I suggest is to ask team members to provide high quality images.

**Comment by tschaffter** [comment]
Random notes:

- We have `AUTO_PNG_TO_JPG=True` in `.env`, see [`.env.example`](https://github.com/Sage-Bionetworks/sage-monorepo/blob/main/apps/openchallenges/thumbor/.env.example#L24)
- We could ultimately let the user decide on the format, e.g. webp (best ratio quality-file size), png/jpg (required for search engine optimization)
- We should probably not change the format of the image a few days before the official launch.
- Please ask team members to submit high-quality images if needed. A minimum width and height in pixel should be requested.
