### ISSUE TITLE
[Story] Generate challenge headlines that have less than 80 characters

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2340]
### What product(s) is this story for?

OpenChallenges

### As a user, I want

NA

### Tasks

- [x] Find spec from Google about headlines
- [ ] Update the Python code to generate headlines
- [ ] Generate headlines
- [ ] Share the headlines with Verena and Gaia

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
## Spec

Here is a discussion we had some times ago: #1119 

The recommendation is to have headlines that are no longer than 60 chars. I will start first with this length and see if we get meaningful headlines. Otherwise I will then try >= 80 chars.

**Comment by tschaffter** [comment]
Testing on a sample of the 20 first challenges. AWS Bedrock doesn't generate headlines for most challenges. Also, the LLM does not count the length of the headlines accurately.

<details>
```json
[
  {
    "id": 1,
    "slug": "network-topology-and-parameter-inference",
    "name": "Network Topology and Parameter Inference",
    "headline": "Optimize methods to estimate biology model parameters for Network Topology a...",
    "headline_alternatives": []
  },
  {
    "id": 2,
    "slug": "breast-cancer-prognosis",
    "name": "Breast Cancer Prognosis",
    "headline": "Predict breast cancer survival from clinical and genomic data for Breast Can...",
    "headline_alternatives": []
  },
  {
    "id": 3,
    "slug": "phil-bowen-als-prediction-prize4life",
    "name": "Phil Bowen ALS Prediction Prize4Life",
    "headline": "Seeking treatment to halt ALS's fatal loss of motor function for Phil Bowen ...",
    "headline_alternatives": []
  },
  {
    "id": 4,
    "slug": "drug-sensitivity-and-drug-synergy-prediction",
    "name": "Drug Sensitivity and Drug Synergy Prediction",
    "headline": "Revolutionizing Cancer Therapeutics: Predicting Drug Sensitivity in Human Ce...",
    "headline_alternatives": []
  },
  {
    "id": 5,
    "slug": "niehs-ncats-unc-toxicogenetics",
    "name": "NIEHS-NCATS-UNC Toxicogenetics",
    "headline": "Predicting cytotoxicity from genomic and chemical data for NIEHS-NCATS-UNC T...",
    "headline_alternatives": []
  },
  {
    "id": 6,
    "slug": "whole-cell-parameter-estimation",
    "name": "Whole-Cell Parameter Estimation",
    "headline": "Seeking innovative parameter estimation methods for large models for Whole-C...",
    "headline_alternatives": [
      "1. Seeking innovative parameter estimation for large models (52 characters)",
      "2. Developing optimization for informative experiment selection (59 characters)",
      "3. Collaborate on parameter estimation of heterogeneous models (59 characters) ",
      "4. Compare approaches to optimize large model parameters (59 characters)",
      "5. Explore parameter estimation methods for complex models (59 characters)"
    ]
  },
  {
    "id": 7,
    "slug": "hpn-dream-breast-cancer-network-inference",
    "name": "HPN-DREAM Breast Cancer Network Inference",
    "headline": "Inferring causal signaling networks in breast cancer for HPN-DREAM Breast Ca...",
    "headline_alternatives": []
  },
  {
    "id": 8,
    "slug": "rheumatoid-arthritis-responder",
    "name": "Rheumatoid Arthritis Responder",
    "headline": "Unlocking Anti-TNF Response Predictors: A Crowdsourced Breakthrough in RA Th...",
    "headline_alternatives": []
  },
  {
    "id": 9,
    "slug": "icgc-tcga-dream-mutation-calling",
    "name": "ICGC-TCGA DREAM Mutation Calling",
    "headline": "Crowdsourcing Challenge Seeks to Improve Cancer Mutation Detection for ICGC-...",
    "headline_alternatives": []
  },
  {
    "id": 10,
    "slug": "acute-myeloid-leukemia-outcome-prediction",
    "name": "Acute Myeloid Leukemia Outcome Prediction",
    "headline": "Uncover drivers of AML using clinical and proteomic data for Acute Myeloid L...",
    "headline_alternatives": []
  },
  {
    "id": 11,
    "slug": "broad-dream-gene-essentiality-prediction",
    "name": "Broad-DREAM Gene Essentiality Prediction",
    "headline": "Crowdsourcing Models to Predict Cancer Cell Gene Dependencies for Broad-DREA...",
    "headline_alternatives": []
  },
  {
    "id": 12,
    "slug": "alzheimers-disease-big-data",
    "name": "Alzheimer's Disease Big Data",
    "headline": "Seeking Accurate Predictive Biomarkers for Alzheimer's Diagnosis for Alzheim...",
    "headline_alternatives": []
  },
  {
    "id": 13,
    "slug": "olfaction-prediction",
    "name": "Olfaction Prediction",
    "headline": "Predicting smell from molecule features for Olfaction Prediction",
    "headline_alternatives": [
      "1. Predicting odor from chemical features to understand smell perception (52 characters)",
      "2. Linking molecular properties to odor for fragrance design acceleration (59 characters) ",
      "3. Modeling how molecules transform into smell to elucidate olfaction (58 characters)",
      "4. Predicting scents from chemicals to gain insights into olfactory processes (59 characters)",
      "5. Connecting chemical features to odors for faster fragrance molecule discovery (59 characters)"
    ]
  },
  {
    "id": 14,
    "slug": "prostate-cancer",
    "name": "Prostate Cancer",
    "headline": "Predict survival of docetaxel treatment in mCRPC patients for Prostate Cancer",
    "headline_alternatives": []
  },
  {
    "id": 15,
    "slug": "als-stratification-prize4life",
    "name": "ALS Stratification Prize4Life",
    "headline": "Advancing ALS Treatment: Predicting Disease Progression and Survival with Data.",
    "headline_alternatives": []
  },
  {
    "id": 16,
    "slug": "astrazeneca-sanger-drug-combination-prediction",
    "name": "AstraZeneca-Sanger Drug Combination Prediction",
    "headline": "Predict effective drug combinations using genomic data for AstraZeneca-Sange...",
    "headline_alternatives": []
  },
  {
    "id": 17,
    "slug": "smc-dna-meta",
    "name": "SMC-DNA Meta",
    "headline": "Seeking Most Accurate Somatic Mutation Detection Pipeline for SMC-DNA Meta",
    "headline_alternatives": [
      "1. Seeking most accurate pipeline for detecting cancer mutations (56 characters)",
      "2. Challenge to identify top somatic mutation detection methods (51 characters)",
      "3. Establishing state-of-the-art in cancer mutation detection (51 characters) ",
      "4. Improving accuracy of algorithms that detect cancer mutations (51 characters)",
      "5. Challenge to complement and enhance cancer mutation calling methods (59 characters)"
    ]
  },
  {
    "id": 18,
    "slug": "smc-het",
    "name": "SMC-Het",
    "headline": "Crowdsourcing Challenge to Improve Tumor Subclonal Reconstruction for SMC-Het",
    "headline_alternatives": []
  },
  {
    "id": 19,
    "slug": "respiratory-viral",
    "name": "Respiratory Viral",
    "headline": "Unraveling Viral Susceptibility: Early Predictors of Respiratory Infection a...",
    "headline_alternatives": []
  },
  {
    "id": 20,
    "slug": "disease-module-identification",
    "name": "Disease Module Identification",
    "headline": "Crowdsourcing challenge to find disease modules in genomic networks for Dise...",
    "headline_alternatives": []
  }
]
```
</details>

**Comment by tschaffter** [comment]
```json
[
  {
    "id": 1,
    "slug": "network-topology-and-parameter-inference",
    "name": "Network Topology and Parameter Inference",
    "headline": "Optimize methods to estimate biology model parameters for Network Topology a...",
    "headline_alternatives": []
  },
  {
    "id": 2,
    "slug": "breast-cancer-prognosis",
    "name": "Breast Cancer Prognosis",
    "headline": "Predict breast cancer survival from clinical and genomic data for Breast Can...",
    "headline_alternatives": []
  },
  {
    "id": 3,
    "slug": "phil-bowen-als-prediction-prize4life",
    "name": "Phil Bowen ALS Prediction Prize4Life",
    "headline": "Seeking treatment to halt ALS's fatal loss of motor function for Phil Bowen ...",
    "headline_alternatives": []
  },
  {
    "id": 4,
    "slug": "drug-sensitivity-and-drug-synergy-prediction",
    "name": "Drug Sensitivity and Drug Synergy Prediction",
    "headline": "Revolutionizing Cancer Therapeutics: Predicting Drug Sensitivity in Human Ce...",
    "headline_alternatives": []
  },
  {
    "id": 5,
    "slug": "niehs-ncats-unc-toxicogenetics",
    "name": "NIEHS-NCATS-UNC Toxicogenetics",
    "headline": "Predicting cytotoxicity from genomic and chemical data for NIEHS-NCATS-UNC T...",
    "headline_alternatives": []
  },
  {
    "id": 6,
    "slug": "whole-cell-parameter-estimation",
    "name": "Whole-Cell Parameter Estimation",
    "headline": "Seeking innovative parameter estimation methods for large models for Whole-C...",
    "headline_alternatives": [
      "1. Seeking innovative parameter estimation for large models (52 characters)",
      "2. Developing optimization for informative experiment selection (59 characters)",
      "3. Collaborate on parameter estimation of heterogeneous models (59 characters) ",
      "4. Compare approaches to optimize large model parameters (59 characters)",
      "5. Explore parameter estimation methods for complex models (59 characters)"
    ]
  },
  {
    "id": 7,
    "slug": "hpn-dream-breast-cancer-network-inference",
    "name": "HPN-DREAM Breast Cancer Network Inference",
    "headline": "Inferring causal signaling networks in breast cancer for HPN-DREAM Breast Ca...",
    "headline_alternatives": []
  },
  {
    "id": 8,
    "slug": "rheumatoid-arthritis-responder",
    "name": "Rheumatoid Arthritis Responder",
    "headline": "Unlocking Anti-TNF Response Predictors: A Crowdsourced Breakthrough in RA Th...",
    "headline_alternatives": []
  },
  {
    "id": 9,
    "slug": "icgc-tcga-dream-mutation-calling",
    "name": "ICGC-TCGA DREAM Mutation Calling",
    "headline": "Crowdsourcing Challenge Seeks to Improve Cancer Mutation Detection for ICGC-...",
    "headline_alternatives": []
  },
  {
    "id": 10,
    "slug": "acute-myeloid-leukemia-outcome-prediction",
    "name": "Acute Myeloid Leukemia Outcome Prediction",
    "headline": "Uncover drivers of AML using clinical and proteomic data for Acute Myeloid L...",
    "headline_alternatives": []
  },
  {
    "id": 11,
    "slug": "broad-dream-gene-essentiality-prediction",
    "name": "Broad-DREAM Gene Essentiality Prediction",
    "headline": "Crowdsourcing Models to Predict Cancer Cell Gene Dependencies for Broad-DREA...",
    "headline_alternatives": []
  },
  {
    "id": 12,
    "slug": "alzheimers-disease-big-data",
    "name": "Alzheimer's Disease Big Data",
    "headline": "Seeking Accurate Predictive Biomarkers for Alzheimer's Diagnosis for Alzheim...",
    "headline_alternatives": []
  },
  {
    "id": 13,
    "slug": "olfaction-prediction",
    "name": "Olfaction Prediction",
    "headline": "Predicting smell from molecule features for Olfaction Prediction",
    "headline_alternatives": [
      "1. Predicting odor from chemical features to understand smell perception (52 characters)",
      "2. Linking molecular properties to odor for fragrance design acceleration (59 characters) ",
      "3. Modeling how molecules transform into smell to elucidate olfaction (58 characters)",
      "4. Predicting scents from chemicals to gain insights into olfactory processes (59 characters)",
      "5. Connecting chemical features to odors for faster fragrance molecule discovery (59 characters)"
    ]
  },
  {
    "id": 14,
    "slug": "prostate-cancer",
    "name": "Prostate Cancer",
    "headline": "Predict survival of docetaxel treatment in mCRPC patients for Prostate Cancer",
    "headline_alternatives": []
  },
  {
    "id": 15,
    "slug": "als-stratification-prize4life",
    "name": "ALS Stratification Prize4Life",
    "headline": "Advancing ALS Treatment: Predicting Disease Progression and Survival with Data.",
    "headline_alternatives": []
  },
  {
    "id": 16,
    "slug": "astrazeneca-sanger-drug-combination-prediction",
    "name": "AstraZeneca-Sanger Drug Combination Prediction",
    "headline": "Predict effective drug combinations using genomic data for AstraZeneca-Sange...",
    "headline_alternatives": []
  },
  {
    "id": 17,
    "slug": "smc-dna-meta",
    "name": "SMC-DNA Meta",
    "headline": "Seeking Most Accurate Somatic Mutation Detection Pipeline for SMC-DNA Meta",
    "headline_alternatives": [
      "1. Seeking most accurate pipeline for detecting cancer mutations (56 characters)",
      "2. Challenge to identify top somatic mutation detection methods (51 characters)",
      "3. Establishing state-of-the-art in cancer mutation detection (51 characters) ",
      "4. Improving accuracy of algorithms that detect cancer mutations (51 characters)",
      "5. Challenge to complement and enhance cancer mutation calling methods (59 characters)"
    ]
  },
  {
    "id": 18,
    "slug": "smc-het",
    "name": "SMC-Het",
    "headline": "Crowdsourcing Challenge to Improve Tumor Subclonal Reconstruction for SMC-Het",
    "headline_alternatives": []
  },
  {
    "id": 19,
    "slug": "respiratory-viral",
    "name": "Respiratory Viral",
    "headline": "Unraveling Viral Susceptibility: Early Predictors of Respiratory Infection a...",
    "headline_alternatives": []
  },
  {
    "id": 20,
    "slug": "disease-module-identification",
    "name": "Disease Module Identification",
    "headline": "Crowdsourcing challenge to find disease modules in genomic networks for Dise...",
    "headline_alternatives": []
  }
]
```
