### ISSUE TITLE
[Task] Create a product workspace for iAtlas

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2405]
### Description

An objective of iAtlas is to consolidate the components of its stack in a single place. The approach proposed is to do this work in Sage Monorepo. If needed, iAtlas could then be exported as its own monorepo.

### Tasks

- [ ] Update the issue templates to list iAtlas as a project
- [x] Link [iAtlas Monorepo](https://github.com/orgs/Sage-Bionetworks/projects/65) project to Sage Monorepo
- [ ] Create an empty project `iatlas-api`

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
