### ISSUE TITLE
[Story] Refactor CI/CD to support e2e and deployment to AWS

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2435]
### What product(s) is this story for?

Sage Monorepo

### Description

We need to:

- Refactor the CI/CD workflow so make it more modular
  - The current implementation involve a long file and lot of duplicated code that could lead to issues.
- We need to run tasks that have access to project-specific secrets
  - The secrets should only be exposed to the projects and tasks that needs them.
  - Example: `schematic-api` e2e test requires secrets to access Synapse
    - Should we use Synapse secrets or use another way to authenticate (OIDC?)
 - The deployment of OC to AWS should be done through the CI/CD workflow
   - OC uses the CDK for Terraform (CDKTF) to deploy the stack.
   - Need to identify how to deploy the following environments `staging` and `production`
   - Additional environment `development` and `testing` should be considered (see [Microsoft docs](https://learn.microsoft.com/en-us/biztalk/technical-guides/planning-the-development-testing-staging-and-production-environments))

Other considerations:

- We are developing inside a monorepo
  - Only a project affected by a change should be processed by the CI/CD and deployed
  - Creating separate monorepo CI/CD pipelines with GitHub Actions
- We use the Forking workflow
  - GH secrets are not available to PRs opened from forks
  - Enabling maintainers to manually allow workflows would be nice, but that seems to be [possible only for private forks](https://docs.github.com/en/enterprise-cloud@latest/actions/managing-workflow-runs/approving-workflow-runs-from-private-forks)?

References:

- [AWS CodePipeline (CI / CD) Tutorial with CDK](https://youtu.be/EVDw0sdxaec?feature=shared) (video)
  - Deployment of the different stages is defined in the `CodePipeline`
- [Multi-Stack Deployments with CDK for Terraform](https://www.youtube.com/live/WdicN25Fkec?feature=shared) (video)

### Acceptance criteria

TBA

### Tasks

- [x] Identify the deployment environment OC needs
- [x] Review [Creating separate monorepo CI/CD pipelines with GitHub Actions](https://blog.logrocket.com/creating-separate-monorepo-ci-cd-pipelines-github-actions/)
- [x] Review [GitHub Actions: Reusable workflows are generally available](https://github.blog/changelog/2021-11-24-github-actions-reusable-workflows-are-generally-available/)
- [ ] Identify if schematic e2e execution can be limited to only Schematic contributors? Otherwise, can it be limited to a subset of schematic developers or a different set of users?
- [ ] TBA

### Anything else?

cc @andrewelamb 

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
## About environments

- You should, however, conduct your performance testing in a physical environment with hardware and software that is identical to the production environment.

**Comment by tschaffter** [comment]
## Branching strategies

- We use
  - Git Forking workflow
  - Trunk Base Development Branching Model

**Comment by tschaffter** [comment]
## Review [Creating separate monorepo CI/CD pipelines with GitHub Actions](https://blog.logrocket.com/creating-separate-monorepo-ci-cd-pipelines-github-actions/)

**Comment by tschaffter** [comment]
## Enable approval for workflow runs from forks in GitHub Actions

Current settings:

<img width="1121" alt="image" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/04c98f33-27af-4f54-900e-771cc8096c54">

Google Bard:

 **Here's a guide on how to run e2e tests with GitHub Workflows in a forking workflow:**

**1. Create or Update a Workflow File:**

- In your repository's `.github/workflows` directory, create or update a YAML file defining your workflow.
- Specify the events that will trigger the workflow, such as pull requests or pushes to specific branches.

**2. Configure Actions for E2E Tests:**

- Within the workflow file, use GitHub Actions to set up the environment for running your tests:
    - Install dependencies for your testing framework.
    - Build your application if necessary.
    - Start any required services or emulators.
- Choose appropriate actions for your testing needs (e.g., `actions/setup-node`, `actions/setup-java`, etc.).

**3. Run the E2E Tests:**

- Use a dedicated action for executing your test suite.
- Consider options like:
    - `actions/github-script`: Directly run test commands within the workflow.
    - Framework-specific actions: Leverage actions tailored for your testing framework (e.g., `cypress-io/github-action` for Cypress).

**4. Customize Actions for Forked Repositories:**

- **Approval Requirements:** Enable approval for workflow runs from forks to ensure security and prevent unwanted actions.
- **Conditional Logic:** Use conditional statements to control workflow execution based on the repository context (e.g., `github.repository_owner`).

**5. Example Workflow File:**

```yaml
name: E2E Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test:e2e
```

**Additional Considerations:**

- **Environment Variables:** Set any necessary environment variables for your tests, including those for external services or test data.
- **Artifacts:** Save test reports and logs as artifacts for inspection and analysis.
- **Caching:** Optimize workflow performance by caching dependencies and build outputs.
- **Security:** Protect sensitive information like API keys using GitHub Secrets.
- **Matrix Builds:** Test across multiple configurations using matrix builds.

**Comment by tschaffter** [comment]
## Enable workflows from forks to access secrets with labels

See https://stackoverflow.com/a/77007901

**Comment by tschaffter** [comment]
Added to Sprint 24.2

**Comment by tschaffter** [comment]
Added to Sprint 24.3
