### ISSUE TITLE
[Task] Add MLCube submission type

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2509]
### What product(s) is this story for?

OpenChallenges

### Description

Add the MLCube submission type as per discussion with MLCommons.

### Tasks

- [x] Add the MLCube submission type
- [x] Update known challenges that use MLCube

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by gaiaandreoletti** [comment]
but are we sure they run challenges? unclear, it seems like they have working group https://mlcommons.org/community/
