### ISSUE TITLE
[Task] Model input data types of challenges with EDAM

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2551]
### What product(s) is this story for?

OpenChallenges

### Description

Refactor #2265 to model input data types as EDAM concepts

### Tasks

- [ ] Update the Data Model
- [ ] Update the API model
- [ ] Update the challenge service
- [ ] Update the API client for Angular
- [ ] Update the web app

Out of scope:

- Index the new properties into ES

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.
