### ISSUE TITLE
[Task] Add Hadolint to the dev container

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2574]
### What product(s) is this story for?

Sage Monorepo

### As a user, I want

As a Developer, I want to get suggestions on how to improve my Dockerfiles as I work on them, so that I can improve them right away.

### Tasks

- [ ] Add Hadolint binary to the dev container (required by the VS Code extension)
- [ ] Add the Hadolint extension for VS Code to the dev container

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
Related to #2572
