### ISSUE TITLE
Evaluate ECS vs EKS

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#258]
## Tasks

- [ ] Learn more about ECS and EKS
- [ ] Compare these two solutions and identify the one that would be the best suited to deploy our applications and services
- [ ] Create slides that summarizes this evaluation

**Comment by tschaffter** [comment]
Using EKS is more align with the spirit of developing a cloud agnostic solution as ECS would lead to an AWS lock-in.
