### ISSUE TITLE
[Epic] Collect challenge metadata for biomedical challenge organizations

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#842]
The goal of this Epic is to manually collect all the relevant information described by our data schema for known organizations that organize biomedical challenges. Examples include MICCAI, precisionFDA and CAMI. The list of challenge data sources identified so far is available [here](https://docs.google.com/spreadsheets/d/1qq7bohgYq3t_bKTRUVhGsmaYhfuQLWT8ZxUGXTuFXL8/edit#gid=0).

The data will be critical when we meet with challenge organizations to promote the adoption of the registry. During the meeting, we could show them a preview of what their organization page and challenge pages would look like.

For large data sources (> 100 challenges) like Kaggle and CodaLab, collecting data would require writing a script that collects data via their API. This work will be tracked in another Epic.

## What information to collect

Refer to the latest version of the OA definition of the challenge registry:

- https://sage-bionetworks.github.io/rocc-schemas/latest/docs/
- https://github.com/Sage-Bionetworks/rocc-schemas

## How format to use

Ultimately as JSON files so that we can easily seed the DB when needed.

## How much data

We don't need to capture the data of all the challenges of an organization for the sake of the preview. At this stage it is more important to get a sample of data from all the organizations than all the data from a handful of organizations. For each organization, collect the following data:

- Organization info (name, description, team members)
- Data from 5 recent challenges

## Which data sources to collect data from

- [x] Collect a sample of data from MICCAI challenges
- [x] Collect a sample of data from precisionFDA challenges
- [x] Collect a sample of data from CAMI challenges
- [ ] TBD

> **Note**
> Convert the above items to tasks when needed.

**Comment by chepyle** [comment]
Reference for MICCAI to register new challenges: https://www.biomedical-challenges.org/ , some more info on grand-challenge.org API: https://grand-challenge.org/api/

**Comment by tschaffter** [comment]
This activity will probably be on until the release of the closed beta (Sprint 23.03).

**Comment by vpchung** [comment]
Curated 5 of precisionFDA's more recent challenges (unfortunately, none are currently active 😢 ) - will add to the db shortly.
